version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: vehicle_tale_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vehicle_tale
      MYSQL_USER: vehicle_user
      MYSQL_PASSWORD: vehicle_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: 